[2023-12-23 17:03:20] [INFO    ] discord.client: logging in using static token
[2023-12-23 17:03:20] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: def01f6a3f108b867e484cfbb0fab4cd).
[H[2J[3J[2023-12-23 17:04:19] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "info" is not found
loading Siege.py
loading DND.py
loading Basic.py
Siege commands loaded
DND commands loaded
Basic commands loaded
4.0
bot-development: DND OVERLORD#5400: DND OVERLORD: I have arrived with version 4.0 loaded
bot-development: DND OVERLORD#5400: DND OVERLORD: 
bot-development: DND OVERLORD#5400: DND OVERLORD: Boot time:2023-12-23 17:03:19
bot-development: kush5683: kush5683: !unshitmypants
bot-development: DND OVERLORD#5400: DND OVERLORD: 
bot-development: kush5683: kush5683: !info
[2023-12-23 17:08:18] [INFO    ] discord.client: logging in using static token
[2023-12-23 17:08:19] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 952f0046f98edc3e567efc007efdcca0).
[H[2J[3J[2023-12-23 17:11:07] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1395, in on_message
    await self.process_commands(message)
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1390, in process_commands
    ctx = await self.get_context(message)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1286, in get_context
    if origin.author.id == self.user.id:  # type: ignore
                           ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
[2023-12-23 17:11:43] [INFO    ] discord.client: logging in using static token
[2023-12-23 17:11:44] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 6a4b4256b2a9e167a12370cf95cdd461).
[H[2J[3J[2023-12-23 17:11:50] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1395, in on_message
    await self.process_commands(message)
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1390, in process_commands
    ctx = await self.get_context(message)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1286, in get_context
    if origin.author.id == self.user.id:  # type: ignore
                           ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
[2023-12-23 17:11:52] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1395, in on_message
    await self.process_commands(message)
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1390, in process_commands
    ctx = await self.get_context(message)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1286, in get_context
    if origin.author.id == self.user.id:  # type: ignore
                           ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
[2023-12-23 17:11:55] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1395, in on_message
    await self.process_commands(message)
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1390, in process_commands
    ctx = await self.get_context(message)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1286, in get_context
    if origin.author.id == self.user.id:  # type: ignore
                           ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
[2023-12-23 17:11:56] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1395, in on_message
    await self.process_commands(message)
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1390, in process_commands
    ctx = await self.get_context(message)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1286, in get_context
    if origin.author.id == self.user.id:  # type: ignore
                           ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
[2023-12-23 17:11:58] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1395, in on_message
    await self.process_commands(message)
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1390, in process_commands
    ctx = await self.get_context(message)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1286, in get_context
    if origin.author.id == self.user.id:  # type: ignore
                           ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
[2023-12-23 17:12:19] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1395, in on_message
    await self.process_commands(message)
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1390, in process_commands
    ctx = await self.get_context(message)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1286, in get_context
    if origin.author.id == self.user.id:  # type: ignore
                           ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
[2023-12-23 17:12:23] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1395, in on_message
    await self.process_commands(message)
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1390, in process_commands
    ctx = await self.get_context(message)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1286, in get_context
    if origin.author.id == self.user.id:  # type: ignore
                           ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
[2023-12-23 17:12:23] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1395, in on_message
    await self.process_commands(message)
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1390, in process_commands
    ctx = await self.get_context(message)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushshah/.local/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1286, in get_context
    if origin.author.id == self.user.id:  # type: ignore
                           ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
[2023-12-23 17:12:27] [INFO    ] discord.client: logging in using static token
[2023-12-23 17:12:28] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 15d1cc68544dca0ba48b804bc356a4ad).
[H[2J[3J